### ISSUE TITLE
Changement de stock d'une déclinaison 

### ISSUE THREAD

**Issue by AyLia85** [shoppingflux/module-prestashop#15]
Au changement de stock d'une déclinaison le stock pris en charge est le stock de l'article et non le stock de la déclinaison 
Dans les logs j'ai cette trace
[Stock token:1] Mise à jour du produit 523 quantité : 527
[Stock token:1] Mise à jour du produit 523_976 quantité : 527
[Stock token:1] Mise à jour du produit 523_993 quantité : 527

L'update du stock n'est donc pas bon dans le flux.

**Comment by yves202** [comment]
fix build 1.4.6
