### ISSUE TITLE
UndefinedMethodException when checking product feed from admin

### ISSUE THREAD

**Issue by amerigeau** [shoppingflux/module-prestashop#206]
Hi,

I'm checking my product feed from admin after fresh install.
The product feed url : https://www.website.com/fr/module/shoppingfeed/product?token=ea0dc99092b42557f54f4f0dbf8c46a4

This generate an error :

_UndefinedMethodException
Attempted to call an undefined method named "setEcotax" of class "ShoppingFeed\Feed\Product\ProductVariation"._

See attached

PrestaShop v1.7.8.6
Module : Shoppingfeed Prestashop Plugin (Feed&Order) v1.8.2 - par 202 ecommerce

Best regards
Arnaud

![Capture d’écran 2022-09-29 à 11 41 16](https://user-images.githubusercontent.com/4548993/192998224-867881bb-6525-45c3-a865-6cc4a48ee472.png)

**Comment by clotairer** [comment]
Sorry @amerigeau I’ve not seen your issue before.

Please apply this patch : 
https://github.com/shoppingflux/module-prestashop/pull/201/files

it will be available on 1.9.0.

thank you
