### ISSUE TITLE
Amazon : permettre la configuration des valeurs "CarrierCode" et "ShippingMethod"

### ISSUE THREAD

**Issue by bpodwinski** [shoppingflux/module-prestashop#247]
Depuis un certain temps, Amazon évalue les vendeurs en fonction de leur taux de suivi valide.

Pour envoyer le numéro de tracking avec le bon transporteur, SF propose une solution :
https://support.shoppingfeed.com/hc/fr/articles/360021448220-Comment-exp%C3%A9dier-correctement-mes-commandes-vers-Amazon-

> Sachez que par défaut nous utilisons la même information pour ces 2 champs, mais il est également possible de les différencier pour envoyer la valeur exacte voulue dans chacun des champs. Pour ce faire, il faudra envoyer dans la confirmation d'expédition de votre système, à travers le nom du transporteur de votre CMS, les 2 valeurs séparées du caractère "/", exemple :
> 
> - Vous nous envoyez dans la confirmation d'expédition (comme nom de transporteur) :
> "LaPoste / Lettre suivie"
> - Nous enverrons : "CarrierCode"= "LaPoste" et "ShippingMethod" = "Lettre suivie".

Dans Prestashop, il est alors nécessaire d'avoir une structure compatible pour les noms des transporteurs, telle que "DPD / Predict", "DPD / DPD Classique".

Pour faciliter le processus, l'idée serait d'ajouter deux colonnes "CarrierCode" et "ShippingMethod" avec un sélecteur qui utilise la liste des valeurs acceptées par Amazon dans le tableau "Correspondance des transporteurs" du module.

https://support.shoppingfeed.com/hc/fr/articles/360021473580-Liste-des-valeurs-accept%C3%A9es-par-Amazon-pour-le-champ-CarrierCode-des-exp%C3%A9ditions
https://support.shoppingfeed.com/hc/fr/articles/360021866099-Liste-des-valeurs-accept%C3%A9es-par-Amazon-pour-le-champ-ShippingMethod-des-exp%C3%A9ditions

**Comment by clotairer** [comment]
Un système d'association de transporteur est en cours de développement au sein du dashboard Shopping Feed. Nous ne développerons donc pas cette fonctionnalité  au sein du module.
Encore merci pour votre suggestion.

L'équipe de développement du module PrestaShop
