### ISSUE TITLE
EcoTax "This value should not be blank"

### ISSUE THREAD

**Issue by dabcorp** [shoppingflux/module-prestashop#262]
Hello,
After update to 1.9.3, can't edit product in BO, no combination is displayed and unable to save.

Error 400 : POST --> https://www.XXX/adminXXX/index.php/sell/catalog/products/59822?_token=6yZtGic9DV7HPdCb2xxlnjBZo4OQ4NCORVrfIOrnsJM#tab-step3

combination_7422_attribute_ecotax | [ "This value should not be blank." ]

After deactivating the module, it works again

**Comment by clotairer** [comment]
Hi,
I've just make a test on a fresh PrestaShop 1.7.8.7. I've no issue. There is probably a conflict with your environment or the configuration.
Could you please contact Shoppingfeed support team support@shopping-flux.com ?

Thank you,
Clotaire
