### ISSUE TITLE
getting error "Be careful, the choice of carrier for the import of shipping costs in the source feed is not filled in (see the "Products feed" tab)"

### ISSUE THREAD

**Issue by pks891618** [shoppingflux/module-prestashop#283]
After installing this module on Prestashop 1.7.6.8 getting below error.

Any help related to this will be appericiated

**"Be careful, the choice of carrier for the import of shipping costs in the source feed is not filled in (see the "Products feed" tab)"**

**Comment by clotairer** [comment]
Hi,
In this interface : 
https://domain.com/admin202/index.php?controller=AdminShoppingfeedGeneralSettings

You should select a carrier : 
![image](https://github.com/shoppingflux/module-prestashop/assets/52157233/a57aa489-90a0-4084-911c-c9934e5d8ca5)
