### ISSUE TITLE
Undefined index: env in OrderImport

### ISSUE THREAD

**Issue by lea-BMS** [shoppingflux/module-prestashop#307]
The `try`, `catch` blocks in `OrderImport/Rules/ShippedByMarketplace.php` are ineffective in silencing accesses to undefined indexes.

Example here: https://github.com/shoppingflux/module-prestashop/blob/develop/src/OrderImport/Rules/ShippedByMarketplace.php#L286C1-L290

**Comment by clotairer** [comment]
Thank you for your report. I merge my issue #308
