### ISSUE TITLE
Compatibilité avec le module SoNice Pro

### ISSUE THREAD

**Issue by marouanehassine** [shoppingflux/module-prestashop#31]
Le module n'est pas compatible au module  SoNice Pro

**Comment by Comval202** [comment]
Bonjour,

Nous allons regarder, nous vous tenons au courant, merci de votre signalement !

**Comment by Comval202** [comment]
Bonjour,

Le module SoNice Pro n'est pas un module officiel, il n'est pour le moment pas prévu dans la road map de rendre le module Shopping Feed compatible avec le module SoNice Pro. 

Bonne journée

**Comment by clotairelims** [comment]
Pour information, il est possible de créer ses propres règle d'import en créant un module qui appelle le hook :
