### ISSUE TITLE
Pourrait-on avoir un peu d'alea dans le chemin du fichier xml ?

### ISSUE THREAD

**Issue by e-gaulue** [shoppingflux/module-prestashop#50]
Bonjour,

Je ne suis pas super enthousiaste à l'idée que n'importe qui puisse télécharger mon flux SF à l'adresse https://url.de.mon.site.fr/file-1.xml.

Certes, ce sont plus ou moins des données publics, mais toutes n'apparaissent pas sur notre site. Qui plus est cela peut faciliter des attaques par ingénierie social. Personne se faisant passer pour nous vis à vis de SF, et surtout l'inverse.

D'où ma question.

Bien à vous,

**Comment by e-gaulue** [comment]
Proposition : 'file-'.md5($token).'.xml'

**Comment by clotairer** [comment]
Bonjour,

La génération d'un fichier XML intermédiaire sera supprimé dans la version 1.8.0. Le flux sera streamé directement.
Nous prévoierons un override qui supprime les fichiers XML devenu inutile.

**Comment by clotairer** [comment]
This issue is closed by [release 1.8.0](https://github.com/shoppingflux/module-prestashop/releases/tag/1.8.0)
