### ISSUE TITLE
🚀 Release 1.4.2

### ISSUE THREAD

**Issue by yves202** [shoppingflux/module-prestashop#7]
[+] Improvment > Let's import shipped orders by marketplaces
[+] Improvment > Add product feed links on account setting admin module page
[+] Improvment > Add hook ShoppingfeedOrderImportCriteria to configure its own order import request
[ *] Fix import order and order status export
[ *] Fix register form displayed in case of multishop
[ *] Fix aknowledgement in case of already imported order not aknowledged
[ *] Frensh translations

**Comment by clotaire202** [comment]
[x] fix cron sync order #25932
